# 🔢 Intro to NumPy

This notebook is a short introduction to **NumPy**, which stands for **Numerical Python**. It is a library for efficient array-based computation in Python and one of the core libraries for scientific computing and machine learning.

At the heart of NumPy is the `ndarray` type, or **NumPy array**, which represents a homogeneous array of values (usually numbers, such as integers or floats). You can think of NumPy arrays as the Python equivalent of vectors, matrices, or tensors in linear algebra. 

Unlike ordinary Python lists, NumPy arrays are designed to support **vectorized operations**, meaning that we can apply operations to whole arrays at once. This makes NumPy code not only shorter and easier to read, but also much faster in practice. Under the hood, many NumPy operations are implemented efficiently in lower-level code.

## 📦 Importing NumPy

Before using NumPy, we need to **import** the library.

Convention:  

`import numpy as np`

- `np` is just a short **alias** — we could use any name, but `np` is standard.  
- After this, every NumPy function is accessed as `np.function(...)` (for example, `np.sin`, `np.arange`).  
- This avoids confusion with other libraries that might also define functions like `sin` or `exp`. 


In [16]:
import numpy as np 

## 🔢 Creating Arrays

There are many ways to create NumPy arrays:

- From Python lists: `np.array([1, 2, 3])`  
- Ranges: `np.arange(start, stop, step)` → like `range`, but returns an array  
- Evenly spaced values: `np.linspace(start, stop, num)`  
- Special arrays:  
  - `np.zeros(shape)` → all zeros  
  - `np.ones(shape)` → all ones  
  - `np.eye(n)` → identity matrix  
  - `np.full(shape, value)` → fill with a constant  

In [17]:
# From a list
a = np.array([1, 2, 3, 4])

# Ranges
ar = np.arange(0, 10, 2)   # 0, 2, 4, 6, 8
lin = np.linspace(0, 1, 5) # 5 points from 0 to 1 inclusive

# Special arrays
zeros = np.zeros((2, 3))
ones  = np.ones((3, 3))
eye   = np.eye(3)
full  = np.full((2, 2), 7)

a, ar, lin, zeros, ones, eye, full


(array([1, 2, 3, 4]),
 array([0, 2, 4, 6, 8]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[7, 7],
        [7, 7]]))

## 📐 Array Attributes

Every NumPy array has a few important attributes:

- `.shape` → the dimensions of the array (rows, cols, …)  
- `.ndim` → the number of dimensions (1D, 2D, 3D, …)  
- `.dtype` → the data type of the elements (e.g. `int64`, `float64`)  
- `.size` → the total number of elements  


In [18]:
a = np.array([1., 2., 3., 4.])
B = np.zeros((3, 4))

a.shape, a.ndim, a.dtype, a.size


((4,), 1, dtype('float64'), 4)

In [19]:
B.shape, B.ndim, B.dtype, B.size

((3, 4), 2, dtype('float64'), 12)

## 🎯 Indexing & Slicing

NumPy arrays use indexing rules similar to Python lists — but extended to multiple dimensions.

- **1D arrays**: `a[0]`, `a[1:4]`  
- **2D arrays**: `A[i, j]` for row `i`, column `j`  
- **Slicing**: `A[:2, 1:]` selects a submatrix  
- **Boolean masks**: select elements that satisfy a condition  
- **Fancy indexing**: select specific indices with lists or arrays


In [20]:
A = np.arange(1, 10).reshape(3, 3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
# Single element
A[0, 2]

np.int64(3)

In [22]:
# Slice submatrix
A[:2, 1:]

array([[2, 3],
       [5, 6]])

In [23]:
# Boolean mask
mask = A % 2 == 0
mask, A[mask]

(array([[False,  True, False],
        [ True, False,  True],
        [False,  True, False]]),
 array([2, 4, 6, 8]))

In [24]:
# Fancy indexing
A[[0, 2], [1, 2]]  # elements (0,1) and (2,2)

array([2, 9])

💡 Slicing in NumPy usually gives a **view**, not a copy. That means changing the slice also changes the original array.

In [25]:
sub = A[:2, :2]
sub[0, 0] = 99
A   # the change appears in A too!

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

## 🧮 Array Math

NumPy arrays support both **elementwise operations** and **matrix-style operations**.

### 🔹 Elementwise
- Arithmetic: `+`, `-`, `*`, `/`, `**` → applied to each element  
- Comparisons: `>`, `<`, `==` → return boolean arrays  
- Universal functions: `np.sin`, `np.exp`, `np.log`, … applied elementwise  

### 🔹 Aggregate functions
- `np.sum`, `np.mean`, `np.max`, `np.min`, `np.std`  
- With `axis` argument: operate along rows or columns  

### 🔹 Matrix-style
- Dot product: `np.dot(a, b)` or `a @ b`  
- Matrix–vector multiplication  
- Matrix–matrix multiplication


In [26]:
x = np.linspace(0, 2*np.pi, 5)

# Elementwise operations
y1 = x**2
y2 = np.sin(x)
y3 = np.exp(-x)

y1, y2, y3

(array([ 0.       ,  2.4674011,  9.8696044, 22.2066099, 39.4784176]),
 array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
        -2.4492936e-16]),
 array([1.        , 0.20787958, 0.04321392, 0.00898329, 0.00186744]))

In [27]:
# Comparisons
mask = (y1 > 5)
mask, y1[mask]

(array([False, False,  True,  True,  True]),
 array([ 9.8696044, 22.2066099, 39.4784176]))

In [28]:
# Aggregates
np.sum(y1), np.mean(y1), np.max(y1)

(np.float64(74.02203300817018),
 np.float64(14.804406601634037),
 np.float64(39.47841760435743))

In [29]:
# Matrix-style multiplication
A = np.array([[1, 2],
              [3, 4]])
b = np.array([10, 20])

# Matrix–vector
A @ b

array([ 50, 110])

In [30]:
# Matrix–matrix
B = np.array([[2, 0],
              [1, 2]])
A @ B

array([[ 4,  4],
       [10,  8]])

💡 Important:
- `*` means elementwise multiplication  
- `@` or `np.dot` means matrix multiplication  


## 🔄 Array Operations

NumPy arrays can be reshaped, transposed, and combined in powerful ways.

### Reshape
- `.reshape(new_shape)` changes the dimensions of an array **without copying data**.  
- Useful for turning a 1D vector into a 2D matrix, etc.

### Transpose
- `.T` gives the transpose: rows ↔ columns.  
- Works for 2D arrays (and higher dimensions).

### Broadcasting
- NumPy automatically “stretches” smaller arrays to match shapes.  
- Lets you write **vector + scalar**, **matrix + vector**, etc. without explicit loops.


In [31]:
# Reshape
arr = np.arange(12)
M = arr.reshape(3, 4)
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
# Transpose
M.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [33]:
# Broadcasting: add vector to each row
v = np.array([1, 2, 3, 4])
M + v

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11],
       [ 9, 11, 13, 15]])

In [34]:
# Broadcasting: scale rows differently
scales = np.array([[1], [2], [3]])  # shape (3,1)
M * scales

array([[ 0,  1,  2,  3],
       [ 8, 10, 12, 14],
       [24, 27, 30, 33]])

💡 Broadcasting rules:
1. Align shapes from the right.  
2. Dimensions must be equal, or one of them must be 1.  
3. NumPy “stretches” the 1 to fit.  

Example: `(3,4)` array + `(4,)` vector → `(3,4)` result.  


## 🧮 Array Math with NumPy Functions

NumPy redefines math functions (`sin`, `cos`, `exp`, …) so they work **elementwise** on arrays.


In [35]:
x = np.linspace(0, 2*np.pi, 5)

np.sin(x), np.cos(x), np.exp(x)

(array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
        -2.4492936e-16]),
 array([ 1.0000000e+00,  6.1232340e-17, -1.0000000e+00, -1.8369702e-16,
         1.0000000e+00]),
 array([  1.        ,   4.81047738,  23.14069263, 111.31777849,
        535.49165552]))

## 🎲 Random Arrays

NumPy includes a powerful random number generator.  

### Common functions:
- `np.random.rand(m, n)` → uniform in [0, 1)  
- `np.random.randn(m, n)` → standard normal distribution (mean 0, std 1)  
- `np.random.randint(low, high, size)` → random integers  
- `np.random.seed(n)` → set the seed for reproducibility  

In [36]:
np.random.seed(0)  # reproducibility

U = np.random.rand(2, 3)      # uniform [0,1)
N = np.random.randn(3, 3)     # normal(0,1)
R = np.random.randint(0, 10, size=(2, 5))  # random integers

U, N, R

(array([[0.5488135 , 0.71518937, 0.60276338],
        [0.54488318, 0.4236548 , 0.64589411]]),
 array([[ 0.95008842, -0.15135721, -0.10321885],
        [ 0.4105985 ,  0.14404357,  1.45427351],
        [ 0.76103773,  0.12167502,  0.44386323]]),
 array([[2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1]], dtype=int32))

## ⚡ Performance: Lists vs NumPy

Python lists are flexible, but NumPy arrays are **faster, more compact, and better suited for numerical computation**.

### Why do arrays outperform lists?

- **Homogeneous data** 
- **Vectorized operations**
- **Lower-level (C) code under the hood** 

In [37]:
import time

# Large dataset
N = 10000000
lst = list(range(N))
arr = np.arange(N)

# Timing with Python list
start = time.time()
squares_list = [x**2 for x in lst]
end = time.time()
print("List comprehension:", end - start, "seconds")

# Timing with NumPy array
start = time.time()
squares_array = arr**2
end = time.time()
print("NumPy array:", end - start, "seconds")


List comprehension: 4.363869905471802 seconds
NumPy array: 0.034296512603759766 seconds
